<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFrameworks>netstandard2.0;net8.0</TargetFrameworks>
        <Version>4.0.0-beta.3</Version>
        <Authors>Ben Hutchison</Authors>
        <Company>$(Authors)</Company>
        <Description>Convert and format data size units (bits, bytes, kilobits, kilobytes, and others).</Description>
        <Copyright>© 2026 $(Authors)</Copyright>
        <PackageProjectUrl>https://github.com/Aldaviva/DataSizeUnits</PackageProjectUrl>
        <RepositoryUrl>https://github.com/Aldaviva/DataSizeUnits.git</RepositoryUrl>
        <PublishRepositoryUrl>true</PublishRepositoryUrl>
        <RepositoryType>git</RepositoryType>
        <PackageLicenseExpression>Apache-2.0</PackageLicenseExpression>
        <PackageTags>data-size data-units file-size storage-space byte kilobyte megabyte gigabyte bit kilobit megabit gigabit</PackageTags>
        <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
        <GenerateDocumentationFile>true</GenerateDocumentationFile>
        <IncludeSource>true</IncludeSource>
        <IncludeSymbols>true</IncludeSymbols>
        <SymbolPackageFormat>snupkg</SymbolPackageFormat>
        <EmbedUntrackedSources>true</EmbedUntrackedSources>
        <LangVersion>latest</LangVersion>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <PackageReadmeFile>Readme.md</PackageReadmeFile>
        <PackageIcon>icon.png</PackageIcon>
        <RestoreEnablePackagePruning>true</RestoreEnablePackagePruning>
    </PropertyGroup>

    <ItemGroup>
        <AdditionalFiles Include="ExceptionAdjustments.txt" />
        <None Include="..\Readme.md;icon.png" Pack="true" PackagePath="\" />
        <None Include="..\.github*\**" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.SourceLink.GitHub" Version="10.0.201" PrivateAssets="All" />
        <PackageReference Include="Newtonsoft.Json" Version="13.0.4" PrivateAssets="All" />
        <PackageReference Include="System.Text.Json" Version="8.0.6" />
    </ItemGroup>

    <PropertyGroup Condition="'$(GITHUB_ACTIONS)' == 'true' or '$(Configuration)' != 'Debug'">
        <ContinuousIntegrationBuild>true</ContinuousIntegrationBuild>
    </PropertyGroup>
    
</Project>