<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFrameworks>netstandard2.0;net5.0</TargetFrameworks>
        <Version>3.0.0-beta2</Version>
        <Authors>Ben Hutchison</Authors>
        <Company>Ben Hutchison</Company>
        <PackageId>DataSizeUnits</PackageId>
        <Product>DataSizeUnits</Product>
        <Description>Convert and format data size units in .NET (bits, bytes, kilobits, kilobytes, and others).</Description>
        <Copyright>© 2025 Ben Hutchison</Copyright>
        <PackageProjectUrl>https://github.com/Aldaviva/DataSizeUnits</PackageProjectUrl>
        <RepositoryUrl>https://github.com/Aldaviva/DataSizeUnits.git</RepositoryUrl>
        <PublishRepositoryUrl>true</PublishRepositoryUrl>
        <RepositoryType>git</RepositoryType>
        <PackageLicenseExpression>Apache-2.0</PackageLicenseExpression>
        <PackageTags>data-size data-units file-size storage-space byte kilobyte megabyte gigabyte bit kilobit megabit gigabit</PackageTags>
        <GeneratePackageOnBuild>false</GeneratePackageOnBuild>
        <GenerateDocumentationFile>true</GenerateDocumentationFile>
        <IncludeSource>true</IncludeSource>
        <IncludeSymbols>true</IncludeSymbols>
        <SymbolPackageFormat>snupkg</SymbolPackageFormat>
        <EmbedUntrackedSources>true</EmbedUntrackedSources>
        <LangVersion>latest</LangVersion>
        <Nullable>enable</Nullable>
        <PackageReadmeFile>Readme.md</PackageReadmeFile>
    </PropertyGroup>

    <ItemGroup>
        <AdditionalFiles Include="ExceptionAdjustments.txt" />
        <None Include="..\Readme.md" Pack="true" PackagePath="\" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.SourceLink.GitHub" Version="8.0.0" PrivateAssets="All" />
    </ItemGroup>

    <PropertyGroup Condition="'$(GITHUB_ACTIONS)' == 'true' or '$(Configuration)' == 'Release'">
        <ContinuousIntegrationBuild>true</ContinuousIntegrationBuild>
    </PropertyGroup>
    
</Project>